#-----------------------------------Leaf对应的配置文件-----------------------------------
[CfgLeaf]
LogLevel        ="debug" #打印日志的等级
LogPath         =""      #日志输出目录
WSAddr          ="0.0.0.0:3664" #websocket服务地址
TCPAddr         ="0.0.0.0:3554" #tcp服务地址
MaxConnNum      =20000            #ws的最大连接数
ConsolePort     =3334            #终端命令端口
#ConnAddrs       =["192.168.1.201:5000"]  #大厅集群地址
ServerName      ="RedPacketSweep"
ChipGactRate    =100000
#----------------------------------超时设置
[CfgTimeOut]
HeartbeatTimeout    = 120  #游戏服和客户端保持心跳的超时时间秒
ConnectTimeout      = 5 #客户端建立连接操作的时间秒
#----------------------------------MongoDB配置信息
[CfgMongoDB]
DBName          ="redpacket_sweep"
DBUrl           ="mongodb://localhost"
DBMaxConnNum    =100